name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: rustup update; rustup target add wasm32-unknown-unknown; cargo install trunk
    # - run: cd www; npm install; npm run build
    # - run: cd vuejs; npm install; npm run build
    # - run: cd vuejs_wasm; npm install; npm run build
    - run: cd yew; trunk build --release
    - run: mkdir yew_investigation
    - run: cp -r www/dist/* yew_investigation
    - run: cp -r vuejs/dist yew_investigation/vuejs
    - run: cp -r vuejs_wasm/dist yew_investigation/vuejs_wasm
    - run: cp -r yew/dist yew_investigation/yew
    - uses: actions/upload-artifact@v3
      with:
        name: dist
        path: ./yew_investigation

